### ISSUE TITLE
undefined name 'from_files'

### ISSUE THREAD

**Issue by cclauss** [matpalm/bnn#1]
flake8 testing of https://github.com/matpalm/bnn on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./sample.py:35:47: F821 undefined name 'from_files'
                  (opts.n, src_directory, len(from_files)))
                                              ^
1     F821 undefined name 'from_files'
1
```

**Comment by matpalm** [comment]
fixed in 2fa4642eebe4eec1891beabda88ec4a589a7b087
