### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by titou26140** [matpalm/bnn#14]
Hello,
First of all, thank you for your work !
I will use your work for a school project but when I launch ./run_sample_training_pipeline.sh but i have a Python error : ValueError: too many values to unpack (expected 2)

![image](https://user-images.githubusercontent.com/17065773/53011020-a8bc2f80-343f-11e9-946d-1cbc65ff484c.png)

The program seems to work on other, so that can be a Python version error.
On my computer i have got the Python 3.7.2 version can you give me yours ?

Thank you in advance.

**Comment by matpalm** [comment]
i think the code was broken for a bit.. can you try to sync and run the script again? sorry about that...

**Comment by titou26140** [comment]
How can I sync it ?

**Comment by matpalm** [comment]
depends on how you cloned the repo, but i'm guessing it's going to be just `git pull origin master`

**Comment by titou26140** [comment]
I already pull but the branch is up to date. The latest commit was 7 days ago.
![image](https://user-images.githubusercontent.com/17065773/53019326-c47e0080-3454-11e9-8714-4a772108a5e6.png)

**Comment by matpalm** [comment]
great. i'm on python 3.5.2 

two questions;

1) do you see this every time you run `run_sample_training_pipeline.sh` ?

2) what version skimage do you have? i'm on 0.13.0

```
python3 -c "import skimage;print(skimage.__version__)"
```

i should add a requirements.txt .... #15

**Comment by titou26140** [comment]
I see this error every time I use run_sample_training_pipeline.sh, and i tested it on 2 computers. Same error. One on Mac Os Mojave and one on ArchLinux.

My skimage is 0.14.2.

I will try to downgrade my python version tomorrow and I will keep you updated.

**Comment by matpalm** [comment]
not sure it's a python version, but something about the `centroid` 

that error implies `region.centroid` is an iterable with >2 elements but  the skimage docs (for all versions) just lists the centroid as being a two tuple... http://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.regionprops

you could stick a `print` in the line above and see what `region.centroid` is ...

**Comment by titou26140** [comment]
Ok, I added a `print(region.centroid)` in utils.py and the value of region.centroid is (255.5, 191.5, 0.0).

![image](https://user-images.githubusercontent.com/17065773/53085926-47aa5f80-3504-11e9-944d-a6fdee41203e.png)

I dont know how skimage work so I can't tell you if this value are good or not.

Thank you for your help.

**Comment by matpalm** [comment]
i'd expect a 2 tuple there, not a 3 tuple. the skimage docs for all versions i've checked (including 0.14) say that centroid from regionprops will be a 2 tuple... i can't explain it sorry

http://scikit-image.org/docs/0.14.x/api/skimage.measure.html#regionprops

**Comment by titou26140** [comment]
So I will try to solve this problem and open a pull request if I solve it.
Thank you !

**Comment by titou26140** [comment]
That's it ! You can merge it. 😄

**Comment by matpalm** [comment]
fixed in #16 
thanks!
