### ISSUE TITLE
Only read image files from folders (train.py, data.py, label_ui.py)

### ISSUE THREAD

**Issue by benjaminjack** [matpalm/bnn#17]
All macOS directories contain a hidden .DS_Store. All scripts now assume that the directories with training data, test data, and label data only contain images, and they read in all files in those directories. This causes the python scripts to crash when it tries to read in a .DS_Store file.

**Comment by matpalm** [comment]
yeah, i dislike macOS immensely for exactly this kind of thing :( something like `find  -name .DS_Store -exec rm -rf {} \;` in my scripts has worked for me in the past on macOS
