### ISSUE TITLE
Skip files without labels

### ISSUE THREAD

**Issue by benjaminjack** [matpalm/bnn#18]
Sometimes you might have an image in your dataset with no bees present. It would be nice if data.py and train.py could automatically skip unlabeled files, assuming that they don't have any bees in them. Or, alternatively, if we could make an image as containing no bees.

**Comment by matpalm** [comment]
this is actually covered already in the data model; an entry in the `imgs` table with no entries in the `labels` table is an image with no bees.  https://github.com/matpalm/bnn/blob/master/label_db.py#L35

unlabelled shouldn't be the same as no bees;
