### ISSUE TITLE
Merge two databases

### ISSUE THREAD

**Issue by titou26140** [matpalm/bnn#20]
Hello when I merge two databases with your script, only the imgs table are merged not the labels table.
How can we label a set of data with several peoples and merge all the labelisation datas ?
Do I have to create an unique Id by image with uuid for exemple to avoid merge error ?

Thank you in advance for your help.

**Comment by matpalm** [comment]
The use case I had was very narrow & so I wrote the minimal code. Having said that, I thought it would generalise ok; I can't think of why labels wouldn't be picked up... The code is pretty short for merge, should be pretty easy to debug; specifically printing out `from_db.imgs()` & `into_db.has_labels(img)`

**Comment by titou26140** [comment]
It's ok, I rewrite the script to generate a unique Id by image, and the merge script to merge imgs and labels table.

**Comment by matpalm** [comment]
I'd be curious to see why it didn't work for you / what you come up with since creating a unique id per image and then copying labels across is what merge does now...
