### ISSUE TITLE
Running into RAM issues with a relatively small dataset

### ISSUE THREAD

**Issue by Helw150** [matpalm/bnn#21]
I'm running into issues where the train script fills up my memory (16GB RAM) with even 900 training examples. I am attempting to utilize the semi-supervised approach described in the blog bost, but capping out on RAM before even using thousands of images.

Is there something I am doing wrong to be able to utilize more images for training? I can't seem to find others struggling with this issue so I assume I have missed a detail somewhere in the blog or the README, but I am unable to find it.

**Comment by matpalm** [comment]
Which step is failing for you?
( Any custom flags? )

**Comment by matpalm** [comment]
Also, is that 16gb main or gpu ram?

First thing to try is a smaller batch size

**Comment by Helw150** [comment]
CPU Memory is filling up during training, I initially had issues with GPU RAM, but those were solved by using the patch training. Below is the command I am currently running for training.
 
```bash
./bnn/train.py --run r12 --steps 1000 --train-steps 50 --batch-size 4 --train-image-dir train/ --test-image-dir test/ --label-dir labels/ --patch-width-height 256 --width 1280 --height 720 --label-db labels.db
```

**Comment by matpalm** [comment]
in data.py there's a data.shuffle(1000)
can you try with a lower number there? say 100

**Comment by Helw150** [comment]
This significantly improves the memory usage! Will it have negative side effects?

**Comment by matpalm** [comment]
I very much doubt you'd see a difference (especially with a small batch
size)

**Comment by Helw150** [comment]
Great, thanks!
