### ISSUE TITLE
How do you save database

### ISSUE THREAD

**Issue by AbhimanyuAryan** [matpalm/bnn#24]
One you label images using

```
./label_ui.py \
--image-dir sample_data/training/ \
--label-db sample_data/labels.db \
--width 768 --height 1024
```

How do you save those label in .db? It just quits there's no db file created in sample_data

**Comment by matpalm** [comment]
the repo comes with one already `sample_data/labels.db`. what do you mean no db file is created? did you delete the one that is already there?

**Comment by AbhimanyuAryan** [comment]
@matpalm yes. I want to start fresh. See how things are happening one-by-one
Also I'm downloading your db from Kaggle. So I can try and learn entire thing. End to end. These concepts are very new for me
