### ISSUE TITLE
Is did you handle new data

### ISSUE THREAD

**Issue by AbhimanyuAryan** [matpalm/bnn#25]
You mentioned 

"first round of trained models hadn't seen this and when it appeared it was a constant false positive

most of this was solved already by data augmentation and none of it was a show stopper. in general the data doesn't have much variation, which is great since that allows us to get away with a simple network and training scheme.
"

How did you took the last trained model & augmented new data on it? Instead of training all of it from scratch?

**Comment by matpalm** [comment]
> How did you took the last trained model 

i use the `predict` script to apply a model to held out data
see https://github.com/matpalm/bnn/blob/master/run_sample_training_pipeline.sh#L48

> augmented new data on it? 

augmentation is covered in the `data.py` pipeline
see https://github.com/matpalm/bnn/blob/master/data.py#L67

>  Instead of training all of it from scratch?

i just always train from scratch, such a tiny model

**Comment by AbhimanyuAryan** [comment]
thanks you @matpalm for quick replies. Much appreciated
