### ISSUE TITLE
Not reading Temp Sensor

### ISSUE THREAD

**Issue by jhaltd** [matpalm/bnn#26]
I've tried adding a DHT22 sensor to my Raspberry Pi, but I can't Hivetool to recognize / read it.  Enabled the sensor in Settings, selected DHT22, specified GPIO 4 (I've tried a dozen GPIOs actually), set intercept to 0 and slope to 1.  When I click reread I get:  Temp F, Humidity%, Dew F, Temp C
null null null null

When I use the example.py script from Adafruit to read the sensor I get:  
Last valid input: 2020-04-29 15:30:40.326392
Temperature: 21.8 C
Humidity: 19.5 %

So the sensor is obviously working.  What am I doing wrong with Hivetool?

**Comment by matpalm** [comment]
i've think you've got the wrong repo sorry
