### ISSUE TITLE
Performance issues in /data.py (by P3)

### ISSUE THREAD

**Issue by DLPerf** [matpalm/bnn#27]
Hello! I've found a performance issue in /data.py: `batch()` should be called before `map()`, which could make your program more efficient. Here is [the tensorflow document](https://tensorflow.google.cn/guide/data_performance?hl=zh_cn#vectorized_mapping) to support it.

Detailed description is listed below:

- `dataset.batch(batch_size)`[(here)](https://github.com/matpalm/bnn/blob/535a67d4578adf1a0036f711a7b369f7031251e2/data.py#L116) should be called before `dataset.map(decode_images, num_parallel_calls=8)`[(here)](https://github.com/matpalm/bnn/blob/535a67d4578adf1a0036f711a7b369f7031251e2/data.py#L97), `dataset.map(random_crop, num_parallel_calls=8)`[(here)](https://github.com/matpalm/bnn/blob/535a67d4578adf1a0036f711a7b369f7031251e2/data.py#L106), `dataset.map(set_explicit_size, num_parallel_calls=8)`[(here)](https://github.com/matpalm/bnn/blob/535a67d4578adf1a0036f711a7b369f7031251e2/data.py#L110) and `dataset.map(augment, num_parallel_calls=8)`[(here)](https://github.com/matpalm/bnn/blob/535a67d4578adf1a0036f711a7b369f7031251e2/data.py#L113).

Besides, you need to check the function called in `map()`(e.g., `augment` called in `dataset.map(augment, num_parallel_calls=8)`) whether to be affected or not to make the changed code work properly. For example, if `augment` needs data with shape (x, y, z) as its input before fix, it would require data with shape (batch_size, x, y, z).

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by matpalm** [comment]
Hi,
Thanks for comment! Yes, usually we do want to batch as early as possible but in this case we can't since a large number of the augmentations aren't vectorised :(
Mat

**Comment by DLPerf** [comment]
OK, 
Thank you anyway~ @matpalm
