### ISSUE TITLE
To distinguish hornet and bees

### ISSUE THREAD

**Issue by klorydryk** [matpalm/bnn#7]
Hello,
I would like to be able to get the position (X-Y) of an hornet trying to catch my bees. How could I use your tool to get this information?
I did some videos of what could see my Pi. I attach an example of what it looks like.
![clipboard02](https://user-images.githubusercontent.com/1232047/45024727-f7187600-b039-11e8-9eea-641e7463cf21.png)
What do you think about it?
Thanks!

**Comment by matpalm** [comment]
if you just want to identify the hornet you can run everything and only label hornets. the general pipeline is described in `run_sample_training_pipeline.sh` it's going to be hard with that image quality though, it's hard to do it as a person even...

**Comment by klorydryk** [comment]
Ok, I'll try to do so. I've recorded a new movie with the camera just on the top of the body of the hive. I hope it is a usefull point of view.
![image](https://user-images.githubusercontent.com/1232047/45408455-abcf1a80-b66c-11e8-9e0a-958a08cef75f.png)
